export const AudioBook_Channels = [
  { channle: "Apple Music", state: true },
  { channle: "AudioBooks NZ", state: true },
  { channle: "Deezer", state: true },
  { channle: "Napster", state: true },
  { channle: "Spotify", state: true },
  { channle: "YouTube Music", state: true },
  { channle: "24Symbols", state: true },
  { channle: "Anyplay", state: true },
  { channle: "AudioBooks.com", state: true },
  { channle: "Barner & Noble", state: true },
  { channle: "BookBeat", state: true },
  { channle: "Chirp", state: true },
  { channle: "EBSCO Information services", state: true },
  { channle: "Google LLC", state: true },
  { channle: "Hoopla", state: true },
  { channle: "Kobo", state: true },
  { channle: "Mackin", state: true },
  { channle: "Odilo", state: true },
  { channle: "Scribd,Inc.", state: true },
  { channle: "Wheelers Book Club Limited", state: true },
  { channle: "3 Leaf Group", state: true },
  { channle: "Apple", state: true },
  { channle: "Audioteka", state: true },
  { channle: "Beek", state: true },
  { channle: "BookMate", state: true },
  { channle: "Cliq Digital", state: true },
  { channle: "eStories", state: true },
  { channle: "Group VI-DA", state: true },
  { channle: "Hummingbird Media", state: true },
  { channle: "Libro.FM", state: true },
  { channle: "Nextory", state: true },
  { channle: "Overdrive", state: true },
  { channle: "StoryTel", state: true },
  { channle: "YouScribe", state: true },
  { channle: "Amazon/Audible", state: true },
  { channle: "Audiobooks Now", state: true },
  { channle: "Baker & Taylor, Inc.", state: true },
  { channle: "Bibliotheca, LLC.", state: true },
  { channle: "Calm Radio", state: true },
  { channle: "DownPour", state: true },
  { channle: "Follett Library Resources", state: true },
  { channle: "hibooks", state: true },
  { channle: "instaread", state: true },
  { channle: "ListnerU", state: true },
  { channle: "Nook", state: true },
  { channle: "Permabound", state: true },
  { channle: "UBook", state: true },
];
